# Generated by Django 5.1.6 on 2025-02-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('net_worth', models.PositiveIntegerField(default=0)),
                ('positive_reviews', models.PositiveIntegerField(default=0)),
                ('books_published', models.PositiveSmallIntegerField(default=0)),
                ('years_experience', models.SmallIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('average_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
